#!/usr/bin/env python3
"""Generate First Solar Module Delivery Coordination Call Agenda PDF."""

from fpdf import FPDF

OUTPUT = "/opt/goliath/projects/three-rivers/reports/2026-02-26-first-solar-coordination-call-agenda.pdf"

# ── Colour palette ──────────────────────────────────────────────────
NAVY   = (22, 48, 82)
DARK   = (33, 37, 41)
ACCENT = (41, 98, 155)
WHITE  = (255, 255, 255)
LIGHT_GRAY = (240, 242, 245)
TABLE_HEADER_BG = (22, 48, 82)
TABLE_ALT_ROW   = (245, 247, 250)
RULE_COLOR = (200, 205, 212)
SECTION_BG = (234, 240, 248)


class AgendaPDF(FPDF):
    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="Letter")
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(left=18, top=15, right=18)

    # ── Header ──────────────────────────────────────────────────────
    def header(self):
        if self.page_no() == 1:
            # Title bar background
            self.set_fill_color(*NAVY)
            self.rect(0, 0, self.w, 38, "F")

            # Title text
            self.set_text_color(*WHITE)
            self.set_font("Helvetica", "B", 16)
            self.set_y(9)
            self.cell(0, 8, "Three Rivers Solar", align="C", new_x="LMARGIN", new_y="NEXT")

            # Dash separator
            self.set_font("Helvetica", "", 15)
            self.cell(0, 7, "First Solar Module Delivery Coordination Call", align="C", new_x="LMARGIN", new_y="NEXT")

            # Subtitle bar
            self.set_fill_color(*ACCENT)
            self.rect(0, 38, self.w, 11, "F")
            self.set_font("Helvetica", "I", 10)
            self.set_y(40)
            self.cell(0, 6, "Agenda & Logistics Planning Checklist  -  Updated with Call Decisions", align="C", new_x="LMARGIN", new_y="NEXT")

            # Meta line
            self.set_text_color(*DARK)
            self.set_y(54)
            self.set_font("Helvetica", "", 8.5)
            meta = (
                "Constraint Owner: Tanner Thatcher    |    "
                "Due Date: March 5, 2026    |    "
                "Constraint: Module Delivery Staging"
            )
            self.cell(0, 5, meta, align="C", new_x="LMARGIN", new_y="NEXT")
            self.ln(3)
        else:
            # Pages 2+: slim header
            self.set_fill_color(*NAVY)
            self.rect(0, 0, self.w, 10, "F")
            self.set_text_color(*WHITE)
            self.set_font("Helvetica", "B", 8)
            self.set_y(2.5)
            self.cell(0, 5, "Three Rivers Solar  --  First Solar Coordination Call Agenda", align="C")
            self.set_text_color(*DARK)
            self.set_y(14)

    # ── Footer ──────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*RULE_COLOR)
        self.line(18, self.h - 14, self.w - 18, self.h - 14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10,
                  f"Generated by Goliath  --  Three Rivers Solar Project Operations          "
                  f"Page {self.page_no()}/{{nb}}",
                  align="C")

    # ── Helpers ─────────────────────────────────────────────────────
    def section_heading(self, number, title):
        """Print a numbered section heading with background band."""
        self.ln(3)
        self.set_fill_color(*SECTION_BG)
        self.set_draw_color(*ACCENT)
        self.set_text_color(*NAVY)
        self.set_font("Helvetica", "B", 11)
        y0 = self.get_y()
        self.rect(18, y0, self.w - 36, 8, "F")
        self.line(18, y0, 18, y0 + 8)  # left accent bar
        self.set_line_width(0.6)
        self.set_draw_color(*ACCENT)
        self.line(18, y0, 18, y0 + 8)
        self.set_line_width(0.2)
        self.set_x(22)
        self.cell(0, 8, f"  {number}. {title}", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_text_color(*DARK)

    def body_text(self, text, indent=0):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*DARK)
        self.set_x(18 + indent)
        self.multi_cell(self.w - 36 - indent, 4.5, text)

    def agenda_item(self, number, title, bullets):
        """Numbered agenda item with bullet sub-items."""
        self.set_font("Helvetica", "B", 9.5)
        self.set_text_color(*NAVY)
        self.set_x(22)
        self.cell(0, 5.5, f"{number}. {title}", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*DARK)
        for b in bullets:
            self.set_x(28)
            # Use a dash as bullet
            self.cell(4, 4.5, "-", new_x="END")
            self.multi_cell(self.w - 54, 4.5, f" {b}")
        self.ln(1.5)


def build_pdf():
    pdf = AgendaPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── SECTION 1: PURPOSE ──────────────────────────────────────────
    pdf.section_heading("1", "PURPOSE")
    pdf.body_text(
        "Coordinate module delivery logistics for 65.445 MWdc of First Solar "
        "Series 7 modules arriving March 16 - May 1, 2026. The team has agreed "
        "to proceed with off-site storage to ensure warranty-compliant module "
        "staging. This document reflects decisions made during the coordination call "
        "and outlines remaining action items for the off-site storage approach."
    )
    pdf.ln(1)

    # ── SECTION 2: MODULE DELIVERY SCHEDULE ─────────────────────────
    pdf.section_heading("2", "MODULE DELIVERY SCHEDULE")

    # Table column widths (total ~174 mm usable)
    col_w = [22, 22, 33, 33, 33]
    headers = ["Delivery #", "MWdc", "Window Start", "Window End", "Deadline"]
    rows = [
        ["1",     "10.000", "3/16/2026", "3/20/2026", "3/20/2026"],
        ["2",     "10.000", "3/23/2026", "3/27/2026", "3/27/2026"],
        ["3",     "10.000", "3/30/2026", "4/3/2026",  "4/3/2026"],
        ["4",     "10.000", "4/6/2026",  "4/10/2026", "4/10/2026"],
        ["5",     "10.000", "4/13/2026", "4/17/2026", "4/17/2026"],
        ["6",     "10.000", "4/20/2026", "4/24/2026", "4/24/2026"],
        ["7",     "5.445",  "4/27/2026", "5/1/2026",  "5/1/2026"],
        ["TOTAL", "65.445", "",          "",          ""],
    ]

    x_start = (pdf.w - sum(col_w)) / 2  # centre the table
    row_h = 6.5

    # Header row
    pdf.set_fill_color(*TABLE_HEADER_BG)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_x(x_start)
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], row_h, h, border=1, align="C", fill=True)
    pdf.ln(row_h)

    # Data rows
    pdf.set_font("Helvetica", "", 8.5)
    for idx, row in enumerate(rows):
        is_total = (row[0] == "TOTAL")
        if is_total:
            pdf.set_fill_color(*NAVY)
            pdf.set_text_color(*WHITE)
            pdf.set_font("Helvetica", "B", 8.5)
            fill = True
        elif idx % 2 == 1:
            pdf.set_fill_color(*TABLE_ALT_ROW)
            pdf.set_text_color(*DARK)
            fill = True
        else:
            pdf.set_text_color(*DARK)
            fill = False

        pdf.set_x(x_start)
        for i, val in enumerate(row):
            pdf.cell(col_w[i], row_h, val, border=1, align="C", fill=fill)
        pdf.ln(row_h)

        if is_total:
            pdf.set_font("Helvetica", "", 8.5)

    # Table footnote
    pdf.ln(1.5)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(100, 100, 100)
    pdf.set_x(x_start)
    pdf.cell(0, 4,
             "All modules: First Solar Series 7 Thin Film  |  Delivery windows Mon-Fri  |  7 consecutive weekly deliveries",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    # ── SECTION 3: LOGISTICS & COORDINATION AGENDA ITEMS ────────────
    pdf.section_heading("3", "LOGISTICS & COORDINATION AGENDA ITEMS")

    pdf.agenda_item("1", "Storage & Staging Facility  -  DECIDED: Off-Site Storage", [
        "DECISION: Team agreed to proceed with off-site warehouse storage",
        "Identify and secure off-site warehouse facility - confirm location, lease terms, and availability",
        "Confirm capacity to hold multiple weeks of inventory (10+ MWdc per week, 65.445 MWdc total)",
        "Timeline to prepare facility before March 16 first delivery (18 days out)",
        "Transportation plan: site-to-warehouse and warehouse-to-site logistics",
    ])

    pdf.agenda_item("2", "Loading & Offloading Plan", [
        "Equipment requirements: forklifts, cranes, flatbed access points",
        "Crew sizing and availability for receiving operations",
        "Unloading procedures to minimize handling damage",
    ])

    pdf.agenda_item("3", "Truck Count & Delivery Cadence", [
        "Number of trucks per weekly delivery (10 MWdc = how many truckloads?)",
        "Truck type: 53-ft flatbed vs. step-deck",
        "Daily delivery windows and scheduling with carrier",
    ])

    pdf.agenda_item("4", "First Solar Warranty Compliance", [
        "Module tilt angle requirements during storage",
        "Stacking limits and pallet configuration",
        "Protective covering specifications (UV, moisture)",
        "Request written storage/handling guidance from First Solar",
    ])

    pdf.agenda_item("5", "Site Access & Logistics", [
        "Route planning: delivery point to off-site warehouse (distance, road conditions, weight limits)",
        "Route planning: off-site warehouse to project site for installation",
        "Turning radius and access at both off-site warehouse and project site",
        "Required permits or escorts for oversized loads",
        "Delivery hour restrictions at warehouse and site",
    ])

    pdf.agenda_item("6", "Receiving & Inspection Protocol", [
        "Damage inspection procedures on arrival",
        "Manifest verification and serial number logging",
        "Photo documentation requirements",
        "Rejection/claims process for damaged modules",
    ])

    pdf.agenda_item("7", "Module Security (Off-Site Warehouse)", [
        "Fencing and access control at warehouse facility",
        "Lighting for overnight security",
        "Surveillance/camera coverage - confirm if warehouse has existing systems",
        "Key/access management and authorized personnel list",
    ])

    pdf.agenda_item("8", "Insurance & Liability", [
        "Coverage for theft, weather damage, accidental damage at off-site warehouse",
        "Liability transfer point: carrier to warehouse, warehouse to site",
        "Warehouse lease insurance requirements and indemnification",
        "First Solar warranty implications for off-site storage conditions",
    ])

    # ── SECTION 4: KEY DECISIONS ──────────────────────────────────────
    pdf.section_heading("4", "KEY DECISIONS FROM CALL")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*NAVY)
    pdf.set_x(22)
    pdf.cell(4, 5, "-")
    pdf.cell(0, 5, "  Off-site warehouse storage approved by all parties", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK)
    pdf.set_x(22)
    pdf.cell(4, 5, "-")
    pdf.cell(0, 5, "  Owner does not want to push First Solar delivery dates", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── SECTION 5: NEXT STEPS ─────────────────────────────────────
    pdf.section_heading("5", "NEXT STEPS")
    next_steps = [
        "Identify and secure off-site warehouse (Tanner Thatcher)",
        "Obtain First Solar written storage/handling requirements",
        "Finalize truck count, delivery cadence, and offloading plan",
        "Establish receiving & inspection protocol for warehouse",
        "Confirm insurance coverage for off-site warehouse storage",
        "Set up security measures at warehouse facility",
    ]
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK)
    for s in next_steps:
        pdf.set_x(24)
        pdf.cell(4, 5, "-")
        pdf.cell(0, 5, f"  {s}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── SECTION 6: ATTENDEES ────────────────────────────────────────
    pdf.section_heading("6", "ATTENDEES")
    attendees = [
        "Tanner Thatcher (PM / Constraint Owner)",
        "First Solar Representative",
        "Site Superintendent",
        "Logistics / Procurement Lead",
    ]
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK)
    for a in attendees:
        pdf.set_x(24)
        pdf.cell(4, 5, "-")
        pdf.cell(0, 5, f"  {a}", new_x="LMARGIN", new_y="NEXT")

    # ── Save ────────────────────────────────────────────────────────
    pdf.output(OUTPUT)
    print(f"PDF saved to {OUTPUT}")
    print(f"Pages: {pdf.pages_count}")


if __name__ == "__main__":
    build_pdf()
